# Generated by Django 4.1.2 on 2022-10-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Mens Wear', 'Mens Wear'), ('Womens Wear', 'Womens Wear'), ('Electronics', 'Electronics'), ('Home Appliances', 'Home Appliances'), ('Kids Wear', 'Kids Wear'), ('Decors & Gardening', 'Decors & Gardening'), ('Accessories', 'Accessories')], max_length=26),
        ),
    ]
