# Generated by Django 4.1.3 on 2023-01-19 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_shippinglocation_cart_shippinglocation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Guitar', ' Acoustic Guitar'), ('Guitar', ' Electric Guitar'), ('Keyboard', 'Electric Keyboards'), ('Drums', 'Drum Set'), ('Flutes', 'Flute'), ('Steel', 'Violin'), ('Studio Equipments', ' Equipments'), ('Pedals', 'Bass Guitars')], max_length=26),
        ),
    ]
