# Generated by Django 4.1.3 on 2023-01-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_product_product_info_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
